/**
 * Swagger Petstore
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package my.service;

import my.service.Error;
import my.service.Pet;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * Swagger Petstore
 *
 * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API tests for PetsApi
 */
public class PetsApiTest {


    private PetsApi api;

    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);

        api = JAXRSClientFactory.create("http://petstore.swagger.io/v1", PetsApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);

        ClientConfiguration config = WebClient.getConfig(client);
    }

    
    /**
     * Create a pet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createPetsTest() {
        Pet pet = null;
        //api.createPets(pet);
        
        // TODO: test validations


    }
    
    /**
     * List all pets
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listPetsTest() {
        Integer limit = null;
        //List<Pet> response = api.listPets(limit);
        //assertNotNull(response);
        // TODO: test validations


    }
    
    /**
     * Info for a specific pet
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void showPetByIdTest() {
        String petId = null;
        //Pet response = api.showPetById(petId);
        //assertNotNull(response);
        // TODO: test validations


    }
    
}
