
package https.soap_service_free_mock_beeceptor_com.countryinfoservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountryInfoPortType", targetNamespace = "https://soap-service-free.mock.beeceptor.com/CountryInfoService")
@XmlSeeAlso({
    https.soap_service_free_mock_beeceptor_com.countryinfoservice.ObjectFactory.class,
    org.w3._2001.xmlschema.ObjectFactory.class
})
public interface CountryInfoPortType {


    /**
     * 
     * @return
     *     returns https.soap_service_free_mock_beeceptor_com.countryinfoservice.ArrayOfContinents
     */
    @WebMethod(operationName = "ListOfContinentsByName", action = "https://soap-service-free.mock.beeceptor.com/CountryInfoService.wso/ListOfContinentsByName")
    @WebResult(name = "ListOfContinentsByNameResult", targetNamespace = "")
    @RequestWrapper(localName = "ListOfContinentsByName", targetNamespace = "https://soap-service-free.mock.beeceptor.com/CountryInfoService", className = "https.soap_service_free_mock_beeceptor_com.countryinfoservice.ListOfContinentsByNameType")
    @ResponseWrapper(localName = "ListOfContinentsByNameResponse", targetNamespace = "https://soap-service-free.mock.beeceptor.com/CountryInfoService", className = "https.soap_service_free_mock_beeceptor_com.countryinfoservice.ListOfContinentsByNameResponseType")
    public ArrayOfContinents listOfContinentsByName();

    /**
     * 
     * @return
     *     returns https.soap_service_free_mock_beeceptor_com.countryinfoservice.ArrayOfCountryNames
     */
    @WebMethod(operationName = "ListOfCountryNamesByName", action = "https://soap-service-free.mock.beeceptor.com/CountryInfoService.wso/ListOfCountryNamesByName")
    @WebResult(name = "ListOfCountryNamesByNameResult", targetNamespace = "")
    @RequestWrapper(localName = "ListOfCountryNamesByName", targetNamespace = "https://soap-service-free.mock.beeceptor.com/CountryInfoService", className = "https.soap_service_free_mock_beeceptor_com.countryinfoservice.ListOfCountryNamesByNameType")
    @ResponseWrapper(localName = "ListOfCountryNamesByNameResponse", targetNamespace = "https://soap-service-free.mock.beeceptor.com/CountryInfoService", className = "https.soap_service_free_mock_beeceptor_com.countryinfoservice.ListOfCountryNamesByNameResponseType")
    public ArrayOfCountryNames listOfCountryNamesByName();

}
