package my.service.impl;

import my.service.*;
import my.service.Pet;

import java.util.List;

/**
 * Swagger Petstore
 *
 * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */
public class PetsApiServiceImpl implements PetsApi {
    /**
     * Create a pet
     *
     */
    public void createPets(Pet pet) {
        // TODO: Implement...

        
    }

    /**
     * List all pets
     *
     */
    public List<Pet> listPets(Integer limit) {
        // TODO: Implement...

        return null;
    }

    /**
     * Info for a specific pet
     *
     */
    public Pet showPetById(String petId) {
        // TODO: Implement...

        return null;
    }

}
